---
title: "Figure 2"
author: "Deepak Tanwar"
date: "<b>Created on:</b> 2021-02-26 <br> <b>Updated on:</b> `r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: tango
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    keep_md: no
    number_sections: no
    fig_width: 8
    fig_height: 8
    fig_caption: true
    df_print: paged
    code_folding: hide
  fontsize: 12pt
  geometry: margin=1in
  documentclass: article
# bibliography: references.bib
link-citations: yes
---


# Libraries and functions
```{r}
source("../00_bin/functions.R")
```

# A
```{r}
data_a <- read.table(file = "input/exceRpt_ReadLengths.txt")
data_a <- data_a/sum(data_a)
data_a$Samples <- rownames(data_a)
data_a_m <- melt(data_a)
data_a_m$variable <- gsub(pattern = "X", replacement = "", x = data_a_m$variable)

data_a_m$value[is.na(data_a_m$value)] <- 0
data_a_m$value[is.nan(data_a_m$value)] <- 0
data_a_m$value[is.infinite(data_a_m$value)] <- 0

ggplot(data_a_m, aes(x = variable, y = value, color = Samples, group = Samples)) +
  geom_line() + scale_color_carto_d()


a <- ggplot(tab, aes(x = `diffAccessibility-logFC`, y = -log10(`diffAccessibility-qvalue`))) +
  geom_point(aes(color = Significant), size = 2, alpha = 0.5) +
  scale_color_manual(values = c("black", "#0072B5FF", "#BC3C29FF")) +
  xlim(
    -(ceiling(max(abs(tab$`diffAccessibility-logFC`)))),
    ceiling(max(abs(tab$`diffAccessibility-logFC`)))
  ) +
  ylim(0, max(-log10(tab$`diffAccessibility-qvalue`), na.rm = TRUE) + 1) +
  xlab(bquote(~ Log[2] ~ "FC")) +
  ylab(bquote(~ -Log[10] ~ adjusted ~ italic(P))) +
  labs(
    title = "",
    subtitle = "", caption = paste0("Total = ", scales::comma(nrow(tab)), " tested regions")
  ) +
  # theme_bw(base_family = "Helvetica") +
  th +
  theme(
    legend.title = element_blank(),
    legend.justification = "bottom",
    legend.margin = margin(0, 0, 0, 0),
    # legend.box.margin = margin(0, 0, -20, 0),
    plot.margin = grid::unit(c(1, 5, 1, 1), "mm"),
    legend.key.size = unit(0, "cm")
  ) +
  geom_vline(
    xintercept = c(-1, 1),
    linetype = "longdash",
    colour = "black",
    size = 0.4
  ) +
  geom_hline(
    yintercept = -log10(0.05),
    linetype = "longdash",
    colour = "black",
    size = 0.4
  ) +
  guides(
    colour = guide_legend(
      order = 1,
      override.aes = list(
        size = 5
      )
    )
  ) +
  scale_shape_manual(
    values = c(
      `Not significant` = 19,
      Positive = 19,
      Negative = 19
    ),
    labels = c(
      `Not significant` = "Not significant",
      Positive = "More acc. in Adult",
      Negative = "Less acc. in Adult"
    )
  ) +
  guides(color = guide_legend(override.aes = list(size = 3, alpha = 1), label.hjust = 0, label.vjust = 0, nrow = 3)) +
  geom_label(
    data = anno, aes(x = x, y = y, label = label),
    color = c("#0072B5FF", "#BC3C29FF"),
    size = 4, angle = 45, fontface = "plain", family = "Helvetica"
  )

a1 <- a + theme(legend.text = element_text(
  colour = "black",
  size = 9,
  margin = margin(r = 0, t = 0, b = 2, l = 0, unit = "pt"),
  vjust = 0, hjust = 0
), panel.grid.major = element_blank(), panel.grid.minor = element_blank())
a2 <- a + theme(legend.text = element_text(
  colour = "black",
  size = 9,
  margin = margin(r = 0, t = 0, b = 2, l = 0, unit = "pt"),
  vjust = 0, hjust = 0
), panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))


ag <- gridExtra::grid.arrange(egg::set_panel_size(p = a, width = unit(6.2, "cm"), height = unit(5.62, "cm")))
ag1 <- gridExtra::grid.arrange(egg::set_panel_size(p = a1, width = unit(6.2, "cm"), height = unit(5.62, "cm")))
ag2 <- gridExtra::grid.arrange(egg::set_panel_size(p = a2, width = unit(6.2, "cm"), height = unit(5.62, "cm")))

ggsave(plot = ag, filename = "output/a.pdf", width = unit(8.5, "in"), height = unit(11, "in"), dpi = 320)
ggsave(plot = ag, filename = "output/a.png", width = unit(8.5, "in"), height = unit(11, "in"), dpi = 320)
ggsave(plot = ag1, filename = "output/a_no_grid.png", width = unit(8.5, "in"), height = unit(11, "in"), dpi = 320)
ggsave(plot = ag2, filename = "output/a_no_grid_no_axis.png", width = unit(8.5, "in"), height = unit(11, "in"), dpi = 320)
```



# B

```{r}
data_b <- read.table("input/exceRpt_biotypeCounts.txt")

int <- c("tRNA", "protein_coding", "miRNA", "snRNA", "retained_intron", "snoRNA", "misc_RNA")
data_b_1 <- data_b[int,]
data_b_2 <- t(data.frame(colSums(data_b[!rownames(data_b) %in% rownames(data_b_1),])))
rownames(data_b_2) <- "other"

data_b_f <- rbind(data_b_1, data_b_2)
rownames(data_b_f) <- c("tRNA", "Protein coding", "miRNA", "snRNA", "Retained intron", "snoRNA", "Misc RNA", "Others")
data_b_f <- (data_b_f / colSums(data_b_f)) * 100
data_b_f$Biotypes <- rownames(data_b_f)
data_b_f$Biotypes <- factor(x = data_b_f$Biotypes, levels = unique(data_b_f$Biotypes)[c(1,3,6,4,2,7,5,8)])
data_b_m <- melt(data_b_f)

data_b_m$variable <- factor(data_b_m$variable, unique(data_b_m$variable)[c(2,4,6,8,9, 1,3,5,7,10)])

b <- ggplot(data_b_m, aes(y = value, x = variable, fill = Biotypes)) +
  geom_bar(position = "fill", stat = "identity") +
  labs(
    title = "",
    x = "",
    y = "",
    fill = "Biotypes"
  ) +
  scale_fill_carto_d(palette = "Safe") +
  th +
  theme(axis.text.x = element_text(size = 8, angle = 90), axis.ticks.x = element_blank())

bg <- gridExtra::grid.arrange(egg::set_panel_size(p = b, width = unit(4, "cm"), height = unit(4.5, "cm")))

ggsave(plot = bg, filename = "output/b.pdf", width = unit(8.5, "in"), height = unit(11, "in"), dpi = 320)
ggsave(plot = bg, filename = "output/b.png", width = unit(8.5, "in"), height = unit(11, "in"), dpi = 320)
ggsave(plot = bg, filename = "output/b.eps", width = unit(8.5, "in"), height = unit(11, "in"), dpi = 320)
```

# D
```{r}
pos <- data.frame(read_xlsx("input/2_DIANE_positive_logFC_miRNA_pathways_DIANE.xlsx"))
pos$Category <- "Up regulated in MSUS"
pos$pathway <- gsub(pattern = "\\(.*", replacement = "", x = pos$pathway)
pos$miRNA <- gsub(pattern = "mmu-|\\|.*", replacement = "", x = pos$miRNA)

neg <- data.frame(read_xlsx("input/3_DIANE_negative_logFC_miRNA_pathways_DIANE.xlsx"))
neg$Category <- "Down regulated in MSUS"
neg$pathway <- gsub(pattern = "\\(.*", replacement = "", x = neg$pathway)
neg$miRNA <- gsub(pattern = "mmu-|\\|.*", replacement = "", x = neg$miRNA)

diff <- data.frame(read_xlsx("input/1_DIANE_DEA_miRNAs_pathway_DIANE.xlsx"))
# diff$Category <- "Down regulated in MSUS"
diff$pathway <- gsub(pattern = "\\(.*", replacement = "", x = diff$pathway)
diff$miRNA <- gsub(pattern = "mmu-|\\|.*", replacement = "", x = diff$miRNA)

diff_n <- data.frame(read_xlsx("input/4_DIANE_DEA_miRNAs_pathway_DIANE_corrected.xlsx"))
# diff$Category <- "Down regulated in MSUS"
diff_n$pathway <- gsub(pattern = "\\(.*", replacement = "", x = diff_n$pathway)
diff_n$miRNA <- gsub(pattern = "mmu-|\\|.*", replacement = "", x = diff_n$miRNA)


df_to_mat <- function(df, lv = 100){
mat <- matrix(data = 0, nrow = length(unique(df$pathway)), ncol = length(unique(df$miRNA)))
colnames(mat) <- unique(df$miRNA)
rownames(mat) <- unique(df$pathway)

for(i in 1:nrow(mat)){
  for(j in 1:ncol(mat)){
    ch1 <- rownames(mat)[i]
    ch2 <- colnames(mat)[j]
    
    p <- df[df$pathway == ch1,]
    p <- p[p$miRNA == ch2,]
    
    if(dim(p)[1] == 0){
      mat[i,j] <- NA
    } else{
      p <- p$miRNA_pathway_p_Value
      p <- as.numeric(gsub(pattern = ">|<", replacement = "", x = p))
      if(p !=0){
      mat[i,j] <- -log10(p)
      } else{
      mat[i,j] <- 100
      }
      
    }
  }
}
return(mat)
}

mat_pos <- df_to_mat(df = pos, lv = 32)
mat_neg <- df_to_mat(df = neg, lv = 45)
mat_diff <- df_to_mat(df = diff, lv = 10)
mat_diff_n <- df_to_mat(df = diff_n, lv = 10)

anno_pos <- data.frame(pos[,1:2])
anno_pos <- anno_pos[!duplicated(anno_pos),]
rownames(anno_pos) <- anno_pos$pathway
anno_pos <- anno_pos[rownames(mat_pos),]
anno_pos$pathway_p_value <- -log10(as.numeric(anno_pos$pathway_p_value))
anno_pos$pathway_p_value[is.na(anno_pos$pathway_p_value)] <- 10


anno_neg <- data.frame(neg[,1:2])
anno_neg <- anno_neg[!duplicated(anno_neg),]
rownames(anno_neg) <- anno_neg$pathway
anno_neg <- anno_neg[rownames(mat_neg),]
anno_neg$pathway_p_value <- -log10(as.numeric(anno_neg$pathway_p_value))
anno_neg$pathway_p_value[is.na(anno_neg$pathway_p_value)] <- 13

anno_diff <- data.frame(diff[,1:2])
anno_diff <- anno_diff[!duplicated(anno_diff),]
rownames(anno_diff) <- anno_diff$pathway
anno_diff <- anno_diff[rownames(mat_diff),]
anno_diff$pathway_p_value <- -log10(as.numeric(anno_diff$pathway_p_value))
anno_diff$pathway_p_value[is.na(anno_diff$pathway_p_value)] <- 13

anno_diff_n <- data.frame(diff_n[,1:2])
anno_diff_n <- anno_diff_n[!duplicated(anno_diff_n),]
rownames(anno_diff_n) <- anno_diff_n$pathway
anno_diff_n <- anno_diff_n[rownames(mat_diff_n),]
anno_diff_n$pathway_p_value <- -log10(as.numeric(anno_diff_n$pathway_p_value))
anno_diff_n$pathway_p_value[is.na(anno_diff_n$pathway_p_value)] <- 13


seriate_mat <- function(mat){
  mat[is.na(mat)] <- 0
  mat[is.nan(mat)] <- 0
  mat[is.infinite(mat)] <- 0
  o <- seriate(max(mat) - mat, method = "PCA")
  mat <- mat[get_order(o, 1), ]
  mat <- mat[, get_order(o, 2)]
  return(mat)
}

mat_pos <- seriate_mat(mat = mat_pos)
mat_neg <- seriate_mat(mat = mat_neg)
mat_diff <- seriate_mat(mat = mat_diff)
mat_diff_n <- seriate_mat(mat = mat_diff_n)


set.seed(95978290)
d1 <- Heatmap(
  matrix = mat_pos,
  col = RColorBrewer::brewer.pal(n = 9, name = "Reds")[2:9],
  cluster_rows = F,
  row_names_side = "left",
  cluster_columns = F,
  clustering_method_columns = "ward.D2",
  show_row_names = T,
  show_column_names = T,
  name = "Enrichment (log)",
  # row_split = ge$Group,
  # column_split = cd[, 1, drop = FALSE],
  # cluster_column_slices = F,
  # show_parent_dend_line = FALSE,
  # row_title = NULL,
  row_names_gp = gpar(fontsize = 8, fontfamily = "Helvetica"),
  column_names_gp = gpar(fontsize = 8, fontfamily = "Helvetica"),
  column_title = NULL,
  column_dend_height = unit(0.5, "cm"),
  use_raster = FALSE,
  left_annotation = rowAnnotation(
    df = anno_pos[, 2, drop = FALSE],
    # col = ,
    simple_anno_size = unit(3, "mm"),
    show_annotation_name = TRUE,
    # annotation_name_side = "right",
    annotation_name_rot = 0,
    annotation_name_gp = gpar(fontsize = 0, fontfamily = "Helvetica"),
    annotation_legend_param = list(
      title = expression(- log[10] ~ "adjusted" ~ italic(P) ~ "(pathway)"),
      at = c(0,5,10),
      title_gp = gpar(fontsize = 10, fontface = "plain", fontfamily = "Helvetica"),
      labels_gp = gpar(fontsize = 8, fontfamily = "Helvetica")
    )
  ),
  height = unit(x = 5.5, units = "cm"), width = unit(x = 2.5, units = "cm"),
  heatmap_legend_param = list(
    at = c(0,15,30),
    title = expression(- log[10] ~ "adjusted" ~ italic(P)),
    legend_height = unit(1, "cm"),
    # title_position = "leftcenter-rot",
    title_gp = gpar(fontsize = 10, fontfamily = "Helvetica"),
    labels_gp = gpar(fontsize = 8, fontfamily = "Helvetica")
  )
)

d1



set.seed(95978290)
d2 <- Heatmap(
  matrix = mat_neg,
  col = RColorBrewer::brewer.pal(n = 9, name = "Blues")[2:9],
  cluster_rows = F,
  row_names_side = "left",
  cluster_columns = F,
  clustering_method_columns = "ward.D2",
  show_row_names = T,
  show_column_names = T,
  name = "Enrichment (log)",
  # row_split = ge$Group,
  # column_split = cd[, 1, drop = FALSE],
  # cluster_column_slices = F,
  # show_parent_dend_line = FALSE,
  # row_title = NULL,
  row_names_gp = gpar(fontsize = 8, fontfamily = "Helvetica"),
  column_names_gp = gpar(fontsize = 8, fontfamily = "Helvetica"),
  column_title = NULL,
  column_dend_height = unit(0.5, "cm"),
  use_raster = FALSE,
  left_annotation = rowAnnotation(
    df = anno_neg[, 2, drop = FALSE],
    # col = ,
    simple_anno_size = unit(3, "mm"),
    show_annotation_name = TRUE,
    # annotation_name_side = "right",
    annotation_name_rot = 0,
    annotation_name_gp = gpar(fontsize = 0, fontfamily = "Helvetica"),
    annotation_legend_param = list(
      title = expression(- log[10] ~ "adjusted" ~ italic(P) ~ "(pathway)"),
      at = c(0,5,10),
      title_gp = gpar(fontsize = 10, fontface = "plain", fontfamily = "Helvetica"),
      labels_gp = gpar(fontsize = 8, fontfamily = "Helvetica")
    )
  ),
  height = unit(x = 5.5, units = "cm"), width = unit(x = 4.5, units = "cm"),
  heatmap_legend_param = list(
    at = c(0,15,30),
    title = expression(- log[10] ~ "adjusted" ~ italic(P)),
    legend_height = unit(1, "cm"),
    # title_position = "leftcenter-rot",
    title_gp = gpar(fontsize = 10, fontfamily = "Helvetica"),
    labels_gp = gpar(fontsize = 8, fontfamily = "Helvetica")
  )
)

d2


set.seed(95978290)
d3 <- Heatmap(
  matrix = mat_diff,
  col = rcartocolor::carto_pal(n = 9, "Mint"),
  cluster_rows = F,
  row_names_side = "left",
  cluster_columns = T,
  clustering_method_columns = "ward.D2",
  show_row_names = T,
  show_column_names = T,
  name = "Enrichment (log)",
  # row_split = ge$Group,
  # column_split = cd[, 1, drop = FALSE],
  # cluster_column_slices = F,
  # show_parent_dend_line = FALSE,
  # row_title = NULL,
  row_names_gp = gpar(fontsize = 10, fontfamily = "Helvetica"),
  column_names_gp = gpar(fontsize = 10, fontfamily = "Helvetica"),
  column_title = NULL,
  column_dend_height = unit(0.5, "cm"),
  use_raster = FALSE,
  left_annotation = rowAnnotation(
    df = anno_diff[, 2, drop = FALSE],
    # col = ,
    simple_anno_size = unit(3, "mm"),
    show_annotation_name = TRUE,
    # annotation_name_side = "right",
    annotation_name_rot = 0,
    annotation_name_gp = gpar(fontsize = 0, fontfamily = "Helvetica"),
    annotation_legend_param = list(
      title = expression(- log[10] ~ "adjusted" ~ italic(P) ~ "(pathway)"),
      at = c(0,8,15),
      title_gp = gpar(fontsize = 12, fontface = "plain", fontfamily = "Helvetica"),
      labels_gp = gpar(fontsize = 10, fontfamily = "Helvetica")
    )
  ),
  height = unit(x = 8, units = "cm"), width = unit(x = 6, units = "cm"),
  heatmap_legend_param = list(
    at = c(0,15,30),
    title = expression(- log[10] ~ "adjusted" ~ italic(P)),
    legend_height = unit(1, "cm"),
    # title_position = "leftcenter-rot",
    title_gp = gpar(fontsize = 12, fontfamily = "Helvetica"),
    labels_gp = gpar(fontsize = 10, fontfamily = "Helvetica")
  )
)


d3


set.seed(95978290)
d4 <- Heatmap(
  matrix = mat_diff_n,
  col = rcartocolor::carto_pal(n = 9, "Mint"),
  cluster_rows = F,
  row_names_side = "left",
  cluster_columns = F,
  clustering_method_columns = "ward.D2",
  show_row_names = T,
  show_column_names = T,
  name = "Enrichment (log)",
  # row_split = ge$Group,
  # column_split = cd[, 1, drop = FALSE],
  # cluster_column_slices = F,
  # show_parent_dend_line = FALSE,
  # row_title = NULL,
  row_names_gp = gpar(fontsize = 8, fontfamily = "Helvetica"),
  column_names_gp = gpar(fontsize = 8, fontfamily = "Helvetica"),
  column_title = NULL,
  column_dend_height = unit(0.5, "cm"),
  use_raster = FALSE,
  left_annotation = rowAnnotation(
    df = anno_diff_n[, 2, drop = FALSE],
    # col = ,
    simple_anno_size = unit(3, "mm"),
    show_annotation_name = TRUE,
    # annotation_name_side = "right",
    annotation_name_rot = 0,
    annotation_name_gp = gpar(fontsize = 0, fontfamily = "Helvetica"),
    annotation_legend_param = list(
      title = expression(- log[10] ~ "adjusted" ~ italic(P) ~ "(pathway)"),
      at = c(1,3,5),
      title_gp = gpar(fontsize = 10, fontface = "plain", fontfamily = "Helvetica"),
      labels_gp = gpar(fontsize = 8, fontfamily = "Helvetica")
    )
  ),
  height = unit(x = 2, units = "cm"), width = unit(x = 1.5, units = "cm"),
  heatmap_legend_param = list(
    at = c(0,4,8),
    title = expression(- log[10] ~ "adjusted" ~ italic(P)),
    legend_height = unit(1, "cm"),
    # title_position = "leftcenter-rot",
    title_gp = gpar(fontsize = 10, fontfamily = "Helvetica"),
    labels_gp = gpar(fontsize = 8, fontfamily = "Helvetica")
  )
)

d4


pdf(file = "output/d_up.pdf", width = 11, height = 8.5)
draw(
  object = d1,
  heatmap_legend_side = "right",
  annotation_legend_side = "right",
  merge_legends = TRUE,
  align_annotation_legend = ""
)
dev.off()

png(filename = "output/d_up.png", width = 11, height = 8.5, units = "in", res = 330)
draw(
  object = d1,
  heatmap_legend_side = "right",
  annotation_legend_side = "right",
  merge_legends = TRUE,
  align_annotation_legend = ""
)

dev.off()


postscript(file = "output/d_up.eps", width = 11, height = 8.5)
draw(
  object = d1,
  heatmap_legend_side = "right",
  annotation_legend_side = "right",
  merge_legends = TRUE,
  align_annotation_legend = ""
)
dev.off()


pdf(file = "output/d_down.pdf", width = 11, height = 8.5)
draw(
  object = d2,
  heatmap_legend_side = "right",
  annotation_legend_side = "right",
  merge_legends = TRUE,
  align_annotation_legend = ""
)
dev.off()

png(filename = "output/d_down.png", width = 11, height = 8.5, units = "in", res = 330)
draw(
  object = d2,
  heatmap_legend_side = "right",
  annotation_legend_side = "right",
  merge_legends = TRUE,
  align_annotation_legend = ""
)

dev.off()


postscript(file = "output/d_down.eps", width = 11, height = 8.5)
draw(
  object = d2,
  heatmap_legend_side = "right",
  annotation_legend_side = "right",
  merge_legends = TRUE,
  align_annotation_legend = ""
)
dev.off()



pdf(file = "output/diff_miRNA.pdf", width = 11, height = 8.5)
draw(
  object = d3,
  heatmap_legend_side = "right",
  annotation_legend_side = "right",
  merge_legends = TRUE,
  align_annotation_legend = ""
)
dev.off()

png(filename = "output/diff_miRNA.png", width = 11, height = 8.5, units = "in", res = 330)
draw(
  object = d3,
  heatmap_legend_side = "right",
  annotation_legend_side = "right",
  merge_legends = TRUE,
  align_annotation_legend = ""
)

dev.off()


postscript(file = "output/diff_miRNA.eps", width = 11, height = 8.5)
draw(
  object = d3,
  heatmap_legend_side = "right",
  annotation_legend_side = "right",
  merge_legends = TRUE,
  align_annotation_legend = ""
)
dev.off()



pdf(file = "output/diff_miRNA_new.pdf", width = 11, height = 8.5)
draw(
  object = d4,
  heatmap_legend_side = "right",
  annotation_legend_side = "right",
  merge_legends = TRUE,
  align_annotation_legend = ""
)
dev.off()

png(filename = "output/diff_miRNA_new.png", width = 11, height = 8.5, units = "in", res = 330)
draw(
  object = d4,
  heatmap_legend_side = "right",
  annotation_legend_side = "right",
  merge_legends = TRUE,
  align_annotation_legend = ""
)

dev.off()


postscript(file = "output/diff_miRNA_new.eps", width = 11, height = 8.5)
draw(
  object = d4,
  heatmap_legend_side = "right",
  annotation_legend_side = "right",
  merge_legends = TRUE,
  align_annotation_legend = ""
)
dev.off()
```

## DotPlot
```{r}
pos_neg <- rbind(pos, neg)

pos_neg$miRNA_pathway_p_Value <- -log10(pos_neg$miRNA_pathway_p_Value)
pos_neg$pathway_p_value <- -log10(as.numeric(pos_neg$pathway_p_value))
pos_neg$pathway_p_value[is.na(pos_neg$pathway_p_value)] <- 13

pos_neg$Category <- factor(x = pos_neg$Category, levels = unique(pos_neg$Category))

ont_col <- RColorBrewer::brewer.pal(n = 3, name = "Dark2")

d0 <- ggplot(data = pos_neg, mapping = aes(
  x = miRNA,
  y = pathway,
  color = pathway_p_value,
  size = miRNA_pathway_p_Value
)) +
  geom_point(show.legend = T, alpha = 0.7) +
  # coord_flip(expand = T) +
  # scale_fill_distiller(palette = "Spectral") +
  scale_colour_gradientn(
    colors = rev(myPalette(n = nrow(pos_neg))),
    # colors = rev(cividis(n = nrow(go_df))),
    # guide = guide_colorbar(reverse = TRUE),
    breaks = c(2, 7.5, 13)
  ) +
  scale_size_continuous(breaks = c(10, 25, 40)) +
  xlab("") +
  ylab("") +
  # facet_wrap(~Category, scales = "free_x", labeller = label_wrap_gen(width = 20), nrow = 1) +
  facet_grid(. ~Category, space = "free", scales = "free_x", labeller = label_wrap_gen(width = 15)) +
  th +
  theme(axis.text.x = element_text(size = 7, angle = 90, hjust = 1),
        axis.text.y = element_text(size = 7),
        legend.position = "top")


d0 + guides(
    size = guide_legend(title.position = "top", 
                        title.hjust = 0, 
                        title.vjust = -1, 
                        nrow = 1, size = 8, order = 2,
                        label.vjust = 0.5),
    colour = guide_colorbar(
      nrow = 1, order = 1,
      title.position = "top", title.hjust = -2, title.vjust = -1,
      barwidth = unit(2, "cm"), barheight = unit(0.3, "cm"),
      label.hjust = 0.5, label.vjust = 1, size = 8
    )
  ) +
  labs(
    color = expression(-log[10] ~ "adjusted" ~ italic(P) ~ " "),
    size = expression(-log[10] ~ "adjusted" ~ italic(P) ~ "(pathway)")
  )
d0g <- gridExtra::grid.arrange(egg::set_panel_size(p = d0, width = unit(4.5, "cm"), height = unit(7, "cm")))
ggsave(plot = cg, filename = "output/c.pdf", width = unit(8.5, "in"), height = unit(11, "in"), dpi = 320)
```


```{r}
diff_n$miRNA_pathway_p_Value <- -log10(diff_n$miRNA_pathway_p_Value)
diff_n$pathway_p_value <- -log10(as.numeric(diff_n$pathway_p_value))
diff_n$pathway_p_value[is.na(diff_n$pathway_p_value)] <- 13

# pos_neg$Category <- factor(x = pos_neg$Category, levels = unique(pos_neg$Category))

ont_col <- RColorBrewer::brewer.pal(n = 3, name = "Dark2")

d4_n <- ggplot(data = diff_n, mapping = aes(
  x = miRNA,
  y = pathway,
  color = pathway_p_value,
  size = miRNA_pathway_p_Value
)) +
  geom_point(show.legend = T, alpha = 0.7) +
  # coord_flip(expand = T) +
  # scale_fill_distiller(palette = "Spectral") +
  scale_colour_gradientn(
    colors = rev(myPalette(n = nrow(pos_neg))),
    # colors = rev(cividis(n = nrow(go_df))),
    # guide = guide_colorbar(reverse = TRUE),
    breaks = c(1.6, 4.1)
  ) +
  scale_size_continuous(breaks = c(3, 7)) +
  xlab("") +
  ylab("") +
  # facet_wrap(~Category, scales = "free_x", labeller = label_wrap_gen(width = 20), nrow = 1) +
  # facet_grid(. ~Category, space = "free", scales = "free_x", labeller = label_wrap_gen(width = 15)) +
  th +
  theme(axis.text.x = element_text(angle = 90, hjust = 0),
  legend.position = "top", legend.box = "vertical", legend.text.align = 0) +
  guides(
    size = guide_legend(title.position = "left", 
                        title.hjust = 0, 
                        title.vjust = 0.5, 
                        nrow = 1, size = 4, order = 2,
                        label.vjust = 0.5),
    colour = guide_colorbar(
      nrow = 1, order = 1,
      title.position = "left", title.hjust = 0, title.vjust = 0.5,
      barwidth = unit(1.2, "cm"), barheight = unit(0.3, "cm"),
      label.hjust = 0.5, label.vjust = 2, size = 8
    )
  ) +
  labs(
    color = expression(-log[10] ~ "adjusted" ~ italic(P) ~ " "),
    size = expression(-log[10] ~ "adjusted" ~ italic(P) ~ "(pathway)")
  )

d4ng <- gridExtra::grid.arrange(egg::set_panel_size(p = d4_n, width = unit(2, "cm"), height = unit(3, "cm")))
ggsave(plot = d4ng, filename = "output/d4ng.png", width = unit(8.5, "in"), height = unit(11, "in"), dpi = 320)
```




# C

```{r}
seriate_mat <- function(mat){
  mat[is.na(mat)] <- 0
  mat[is.nan(mat)] <- 0
  mat[is.infinite(mat)] <- 0
  o <- seriate(max(mat) - mat, method = "PCA")
  mat <- mat[get_order(o, 1), ]
  mat <- mat[, get_order(o, 2)]
  return(mat)
}

meta <- data.frame(read_xlsx("./input/metadata_caudaEVs.xlsx"))[1:10,]
meta$group[meta$group == 0] <- "Control"
meta$group[meta$group == 1] <- "MSUS"
rownames(meta) <- meta$sample


files <- list.files(path = "input", pattern = "ReadCounts", full.names = T)
names(files) <- gsub(pattern = "exceRpt_|_ReadCounts.txt", replacement = "", x = basename(files))

data_d <- ldply(lapply(files[-2], function(x){
  a <- read.table(x)
  b <- data.frame(Genes = rownames(a), a)
  return(b)
}), .id = "Biotype")

rownames(data_d) <- data_d$Genes

mm <- model.matrix(~0+Group, data=meta)
y <- DGEList(counts = data_d[,-c(1:2)])
y <- calcNormFactors(y)
cpm <- cpm(y, normalized.lib.sizes = T, log = T)
# rownames(cpm) <- data_d[,2]

# cpm <- t(scale(t(cpm)))
re <- RUVSeq::RUVs(cpm, cIdx=row.names(cpm), k=1, scIdx = RUVSeq::makeGroups(meta$Group), isLog = TRUE)
### add the variable (suppose I have only one) to the colData dataframe:
meta$SV1 <- re$W[,1]
mm <- model.matrix(~SV1+group, data=meta)
y <- y[filterByExpr(y = y, design = mm, min.count=20, min.prop=0.7),]
dds <- estimateDisp(y, mm)
fit <- glmLRT(glmFit(dds, mm), coef = "groupMSUS")
res_DEA <- as.data.frame(topTags(fit,Inf))

cpm2 <- re$normalizedCounts

g <- rownames(res_DEA[res_DEA$PValue <= 0.05,])

meta <- meta[colnames(cpm),]

cpm <- data.matrix(cpm - rowMeans(cpm[, grep(pattern = "MSUS", x = meta$Group, value = F)]))
cpm2 <- data.matrix(cpm2 - rowMeans(cpm2[, grep(pattern = "MSUS", x = meta$Group, value = F)]))

cpm <- seriate_mat(mat = cpm[g,])
cpm2 <- seriate_mat(mat = cpm2[g,])



meta <- meta[colnames(cpm),]

rd <- data_d[,1:2]
rownames(rd) <- rd$Genes
rd <- rd[rownames(cpm),]

colnames(meta)[2] <- "Group"

c <- Heatmap(
  matrix = cpm,
  # col = inferno(100),
  cluster_rows = F,
  row_names_side = "left",
  cluster_columns = F,
  clustering_method_columns = "ward.D2",
  show_row_names = F,
  show_column_names = F,
  name = "Enrichment (log)",
  row_split = rd$Biotype,
  column_split = meta[, 2, drop = FALSE],
  cluster_column_slices = F,
  show_parent_dend_line = FALSE,
  row_title_rot = 0,
  # row_title = NULL,
  row_names_gp = gpar(fontsize = 8, fontfamily = "Helvetica"),
  column_names_gp = gpar(fontsize = 8, fontfamily = "Helvetica"),
  row_title_gp = gpar(fontsize = 8, fontfamily = "Helvetica"),
  column_title = NULL,
  column_dend_height = unit(0.5, "cm"),
  use_raster = FALSE,
  top_annotation = HeatmapAnnotation(
    df = meta[, 2, drop = FALSE],
    col = list(Group = cols[1:2]),
    simple_anno_size = unit(3, "mm"),
    show_annotation_name = TRUE,
    annotation_name_side = "right",
    # title = expression(Log[2] ~ "CPM"),
    annotation_name_rot = 0,
    annotation_name_gp = gpar(fontsize = 0, fontfamily = "Helvetica"),
    annotation_legend_param = list(
      title_gp = gpar(fontsize = 10, fontface = "plain", fontfamily = "Helvetica"),
      labels_gp = gpar(fontsize = 8, fontfamily = "Helvetica")
    )
  ),
  height = unit(x = 4, units = "cm"), width = unit(x = 3, units = "cm"),
  heatmap_legend_param = list(
    at = c(-2,0,2),
    title = expression(Log[2] ~ "FC"),
    legend_height = unit(1, "cm"),
    # title_position = "leftcenter-rot",
    title_gp = gpar(fontsize = 10, fontfamily = "Helvetica"),
    labels_gp = gpar(fontsize = 8, fontfamily = "Helvetica")
  )
)


pdf(file = "output/c.pdf", width = 11, height = 8.5)
draw(
  object = c,
  heatmap_legend_side = "right",
  annotation_legend_side = "right",
  merge_legends = TRUE,
  align_annotation_legend = ""
)
dev.off()

png(filename = "output/c.png", width = 11, height = 8.5, units = "in", res = 330)
draw(
  object = c,
  heatmap_legend_side = "right",
  annotation_legend_side = "right",
  merge_legends = TRUE,
  align_annotation_legend = ""
)

dev.off()


postscript(file = "output/c.eps", width = 11, height = 8.5)
draw(
  object = c,
  heatmap_legend_side = "right",
  annotation_legend_side = "right",
  merge_legends = TRUE,
  align_annotation_legend = ""
)
dev.off()

###############

c2 <- Heatmap(
  matrix = cpm2,
  col = inferno(100),
  cluster_rows = F,
  row_names_side = "left",
  cluster_columns = F,
  clustering_method_columns = "ward.D2",
  show_row_names = F,
  show_column_names = F,
  name = "Enrichment (log)",
  row_split = rd$Biotype,
  column_split = meta[, 2, drop = FALSE],
  cluster_column_slices = F,
  show_parent_dend_line = FALSE,
  row_title_rot = 0,
  # row_title = NULL,
  row_names_gp = gpar(fontsize = 8, fontfamily = "Helvetica"),
  column_names_gp = gpar(fontsize = 8, fontfamily = "Helvetica"),
  row_title_gp = gpar(fontsize = 8, fontfamily = "Helvetica"),
  column_title = NULL,
  column_dend_height = unit(0.5, "cm"),
  use_raster = FALSE,
  top_annotation = HeatmapAnnotation(
    df = meta[, 2, drop = FALSE],
    col = list(Group = cols[1:2]),
    simple_anno_size = unit(3, "mm"),
    show_annotation_name = TRUE,
    annotation_name_side = "right",
    # title = expression(Log[2] ~ "CPM"),
    annotation_name_rot = 0,
    annotation_name_gp = gpar(fontsize = 0, fontfamily = "Helvetica"),
    annotation_legend_param = list(
      title_gp = gpar(fontsize = 10, fontface = "plain", fontfamily = "Helvetica"),
      labels_gp = gpar(fontsize = 8, fontfamily = "Helvetica")
    )
  ),
  height = unit(x = 4, units = "cm"), width = unit(x = 3, units = "cm"),
  heatmap_legend_param = list(
    at = c(-1,0,1),
    title = expression(Log[2] ~ "FC"),
    legend_height = unit(1, "cm"),
    # title_position = "leftcenter-rot",
    title_gp = gpar(fontsize = 10, fontfamily = "Helvetica"),
    labels_gp = gpar(fontsize = 8, fontfamily = "Helvetica")
  )
)

c2

pdf(file = "output/c2.pdf", width = 11, height = 8.5)
draw(
  object = c2,
  heatmap_legend_side = "right",
  annotation_legend_side = "right",
  merge_legends = TRUE,
  align_annotation_legend = ""
)
dev.off()

png(filename = "output/c2.png", width = 11, height = 8.5, units = "in", res = 330)
draw(
  object = c2,
  heatmap_legend_side = "right",
  annotation_legend_side = "right",
  merge_legends = TRUE,
  align_annotation_legend = ""
)

dev.off()


postscript(file = "output/c.eps", width = 11, height = 8.5)
draw(
  object = c,
  heatmap_legend_side = "right",
  annotation_legend_side = "right",
  merge_legends = TRUE,
  align_annotation_legend = ""
)
dev.off()
```

# References
```{r overlap-matrix-rGREAT-43 }
report::cite_packages(session = sessionInfo())
```

# SessionInfo
```{r overlap-matrix-rGREAT-44 }
devtools::session_info() %>%
  details::details()
```
